### ISSUE TITLE
Reference to type 'IHasInputDevices' claims it is defined in 'WebDriver', but it could not be found

### ISSUE THREAD

**Issue by moar** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#1]
Hello,

I just downloaded your library and I am facing this issue and a similar one. I am using the selenium.webdriver 4.1.0 version. Which version should I have?

**Comment by emre-gon** [comment]
You should use Selenium.Webdriver 3.141.0 as of now.

**Comment by emre-gon** [comment]
Updated to Selenium 4
