### ISSUE TITLE
Run  UndetectedChromeDriver with options

### ISSUE THREAD

**Issue by azamatik471** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#11]
How run UndetectedChromeDriver with ChromeOptions?
   using (var driver = UndetectedChromeDriver.Instance())

**Comment by RifHut** [comment]
the same question in issue ticket , check the  [ticket](https://github.com/emre-gon/Selenium.WebDriver.UndetectedChromeDriver/issues/10)!

@emre-gon please dude, help us.

**Comment by emre-gon** [comment]
Added another Instance method for ChromeOptions. 

Update to 2.2.2

**Comment by RifHut** [comment]
Thank You @emre-gon !
