### ISSUE TITLE
Chrome 108 version

### ISSUE THREAD

**Issue by azamatik471** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#14]
Hi! undetected chrome driber doesnt work with chrome 108 version
when ypu can update?

**Comment by azamatik471** [comment]
@emre-gon  When?

**Comment by emre-gon** [comment]
Selenium Chrome driver v108 is not officially released yet: https://chromedriver.chromium.org/downloads

The app will probably have no problems automatically downloading and using the v108 driver once it is officially released.

**Comment by RifHut** [comment]
@emre-gon hi dude, Can I use custom version of ChromeDriver ,I don't need the last Version. is there a way to do this?
