### ISSUE TITLE
[BUG] : undetected_chromedriver.exe window still shown in framework .NET 4.8 (referenced to #5)

### ISSUE THREAD

**Issue by RifHut** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#16]
I'm working in project build with framework .NET 4.8, your project working fine, But Chromedriver window still shown untill the Driver.Quit;

Can you please guide me to solve this issue?
referenced to [#5 ](https://github.com/emre-gon/Selenium.WebDriver.UndetectedChromeDriver/issues/5#issuecomment-1125479610)

**Comment by emre-gon** [comment]
Can you share how you create and dispose the driver?

**Comment by RifHut** [comment]
1 - the driver stored in globale variable as data.Driver 
![image](https://user-images.githubusercontent.com/51222371/200279428-97f4ffc5-2c68-4cbc-8a3d-a1393cc08769.png)
2 - the SIDriver Class Linked with Selenium.Extensions !
![image](https://user-images.githubusercontent.com/51222371/200281244-05bbb8a5-e107-4418-ab8c-6fee8f1ae0c7.png)
3 -The result !
![image](https://user-images.githubusercontent.com/51222371/200281426-74633b7e-3506-4907-88ae-f201819451e2.png)

Thank You in advance @emre-gon !

**Comment by emre-gon** [comment]
You can use Driver.Dispose() when you no longer need the driver and chrome window.

**Comment by RifHut** [comment]
> You can use Driver.Dispose() when you no longer need the driver and chrome window.

I'Il Try soon ,good Job Maan !

**Comment by RifHut** [comment]
> You can use Driver.Dispose() when you no longer need the driver and chrome window.

Dude, Maybe you misunderstood me, At the end all well , I only need to hide the black cmd window, and make it in the silent mode :D !
![image](https://user-images.githubusercontent.com/51222371/200552444-94ba0eb4-2179-485d-9f32-a0369173d149.png)
I want to declare ChromeDriverService inside the undetectedChromeDriver , but does not match with xxx.Instance() !

**Comment by RifHut** [comment]
My issue , Resolved After Adding `service.HideCommandPromptWindow = true;`  to the Selenium.WebDriver.UndetectedChromeDriver.cs

Thank You emre, but we need to call the protected object from foreign class , I wish you the best !
