### ISSUE TITLE
excuse me, have c# or vb.net use the UndetectedChromeDriver "example"?

### ISSUE THREAD

**Issue by averylenies** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#2]
i donwload then add
Imports Selenium.WebDriver.UndetectedChromeDriver

Version 3.141.0

Dim options As ChromeOptions = New ChromeOptions()
Dim driverService = ChromeDriverService.CreateDefaultService()
driverService.HideCommandPromptWindow = True
driverService.SuppressInitialDiagnosticInformation = True
options.AddArgument(“”)..........

Dim driver = New ChromeDriver(driverService, options)
driver.Navigate().GoToUrl("")

don't know UndetectedChromeDriver
how to insert i want bypass 

Redirecting…

DDoS protection by [Cloudflare]

have c# or vb.net full example? want, thanks.

**Comment by emre-gon** [comment]
Just use below code:

```vb
Imports System
Imports Selenium.Extensions
Imports Selenium.WebDriver.UndetectedChromeDriver

Module Program
    Sub Main(args As String())
        Using driver As SlDriver = UndetectedChromeDriver.Instance()
            driver.GoTo("https://google.com")
        End Using
    End Sub
End Module

```

**Comment by averylenies** [comment]
> Just use below code:
> 
> ```vbnet
> Imports System
> Imports Selenium.Extensions
> Imports Selenium.WebDriver.UndetectedChromeDriver
> 
> Module Program
>     Sub Main(args As String())
>         Using driver As SlDriver = UndetectedChromeDriver.Instance()
>             driver.GoTo("https://google.com")
>         End Using
>     End Sub
> End Module
> ```

thanks alreay test success. 

if i want add 
Service.HideCommandPromptWindow = True
options.AddArgument("--headless")    ---wan hide use true.
options.AddArgument("--proxy-server=13.94.36.9:1080")
proxy set also very important

thses set how add to UndetectedChomeDriver have example?

**Comment by emre-gon** [comment]
`UndetectedChromeDriver.Instance(Headless:=True)`

gives a headless driver. Currently there is no option for additional arguments. I will add in the future.

**Comment by averylenies** [comment]
> `UndetectedChromeDriver.Instance(Headless:=True)`
> 
> gives a headless driver. Currently there is no option for additional arguments. I will add in the future.

set Dim driver As SlDriver = UndetectedChromeDriver.Instance(Headless:=True) but still headless=False(set Ture fail)

windows always prompt:
ChromeDriver was started successfully.

DevTools listening on ws://127.0.0.1:52206/devtools/browser/4f84399..........
need hide

hope to solve proxy set and headless=false and HideCommandPromptWindow = True and AddArgument("--user-agent=")
these questions, set very important.

i test several website always bypass “Cloudflare" satisfied.

**Comment by emre-gon** [comment]
I added support for additional arguments. You can download v1.3.3 from Nuget

Usage:

```cs
var args = new HashSet<string>();
args.Add("--incognito");

using (var driver = UndetectedChromeDriver.Instance(args, "profile_name"))
{
 //
}
```
