### ISSUE TITLE
Current browser version is 116.0.5845.111 not supported

### ISSUE THREAD

**Issue by nahueltaibo** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#26]
Hi, 
   I am using this library in one of my projects and I noticed that after chrome updated itself to version 116.0.5845.111, it seems like the library was unable to download a matching Chrome driver, to be modified so it's undetected.

This is the error I am getting:
This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111

**Comment by nahueltaibo** [comment]
I solved this myself, here are the details: Starting on version 115 of chrome, the way drivers are downloaded changed ([here is the official story](https://chromedriver.chromium.org/downloads/version-selection))
So the error is on package [Sl.Selenium.Extensions.Drivers](https://github.com/emre-gon/Sl.Selenium.Extensions.Drivers) as it was not updated to match those changes.

[I created a PR already to fix this](https://github.com/emre-gon/Sl.Selenium.Extensions.Drivers/pull/1). Once it's approved, we should all be able to receive the latest driver automatically again

**Comment by k290** [comment]
For anyone coming across this issue nahueltaibo's fork is here: https://www.nuget.org/packages/NT.Selenium.WebDriver.UndetectedChromeDriver/2.3.2/

Thanks for making this so that we aren't blocked for now with the lib being unusable

**Comment by RifHut** [comment]
Hello @nahueltaibo 
Can you please share with us the source code please ?

**Comment by nahueltaibo** [comment]
Sure, it's a fork of the original repo with the new download process:
https://github.com/nahueltaibo/Selenium.WebDriver.UndetectedChromeDriver
