### ISSUE TITLE
Selam hocam

### ISSUE THREAD

**Issue by kcylmz** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#3]
dostum merhaba. bi otomasyon yazıyorum da otomatik captcha ben normal bi skeilde webdriver kullanırken ITakesScreenshot interfacesini kullandıgımda sorunsuz sayfa ekran görüntüsü çekebiliorum ama senın nuget paketini kullanıp , herhangi bir sayfa açtıgımda bunu tanımladıgım şekilde çekerken hata alıyorum

Kodlar şöyle:
        public SlDriver WebDriver;
WebDriver = UndetectedChromeDriver.Instance("Profile_" + Form1.RandomString(16));
            WebDriver.DriverArguments.Add("--remote-debugging-port=" + Form1.RandomInt(4));
            WebDriver.GoTo("https://www.google.com");

 public void TakeScreenshot(SlDriver driver)
        {
             try
             {
                 Screenshot ss = ((ITakesScreenshot)driver).GetScreenshot();
                 ss.SaveAsFile(Application.StartupPath + @"\captchapng.jpg", OpenQA.Selenium.ScreenshotImageFormat.Jpeg);
             }
             catch (Exception e)
             {
                 Console.WriteLine(e.Message);

             }
            
        }

şöyle bi hata alıyorum:
Exception thrown: 'System.InvalidCastException' in maltaAutomation.exe
Unable to cast object of type 'Selenium.WebDriver.UndetectedChromeDriver.UndetectedChromeDriver' to type 'OpenQA.Selenium.ITakesScreenshot'.

epey uğraştım senin nuget paketini indirip düzenlemeye ama, senin paketine .getScreenshot diye bi komut ekleme şansın ya da paketini nasıl indirip düzenleyebilecegimi kısaca anlatırsan ben de yapabilriim. teşekkürler simdiden

**Comment by kcylmz** [comment]
Hocam şimdi düzenlemeyi başarabildim fakat getScreenshot komudunu senin paketine ekleyemiyorum . yardımcı olabilir misin ? Mailim kcylmz38@gmail.com. ulaşırsan tw veya anydesk vs. verebilirm. saygılar

**Comment by kcylmz** [comment]
yanlıslıkla kapattım

**Comment by emre-gon** [comment]
Paketi 1.3.4'e güncelleyebilirsin. Düzelmiş olması lazım.

**Comment by kcylmz** [comment]
hocam peki service.hidecommantprompwindow nasıl kullanacagım?

**Comment by kcylmz** [comment]
Çok teşekkür ederim bu arada saygılar

**Comment by emre-gon** [comment]
> hocam peki service.hidecommantprompwindow nasıl kullanacagım?

UndetectedChromeDriver classını extend edip CreateBaseDriver methodunu override etmen gerekecek bunun için.
