### ISSUE TITLE
selenium timed out after 60 seconds.

### ISSUE THREAD

**Issue by macasin2003** [emre-gon/Selenium.WebDriver.UndetectedChromeDriver#9]
pleas add 
CreateBaseDriver()
 var driver = new OpenQA.Selenium.Chrome.ChromeDriver(service, options); ->
 var driver = new OpenQA.Selenium.Chrome.ChromeDriver(service, options, TimeSpan.FromSeconds(value));

I use your driver, I have a problem when loading a file through the browser, an error appears.
TimedOut after 60 seconds
I tried adding it manually but nothing helps!
  ISet<string> drv = new HashSet<string>();
   drv.Add("--no-sandbox");

  driver = UndetectedChromeDriver.Instance(drv, opt, Patch + //proffile", false);
             driver.Manage().Timeouts().ImplicitWait.Add(TimeSpan.FromSeconds(6000));
             driver.Manage().Timeouts().PageLoad.Add(TimeSpan.FromSeconds(6000));

Or can you decide differently?

**Comment by emre-gon** [comment]
Update to 2.2.0 and use:

```
var parameters = new ChromeDriverParameters()
{
    Timeout = TimeSpan.FromSeconds(6)
};

using (var driver = UndetectedChromeDriver.Instance(parameters)
{
    driver.GoTo("https://nowsecure.nl");
}
```

**Comment by macasin2003** [comment]
Yes, the solution is good, but not working. The driver will not run in this version (

System.ArgumentNullException: "Value cannot be null.
Parameter name: key"

**Comment by macasin2003** [comment]
ISet<string> opt = new HashSet<string>();
            ISet<string> drv = new HashSet<string>();

            var parameters = new ChromeDriverParameters()
            {
               Timeout = TimeSpan.FromSeconds(6000),
               ProfileName = Patch + "//proffile",
               Headless = false,
               DriverArguments = drv,
               ExcludedArguments = opt

            };

            driver = UndetectedChromeDriver.Instance(parameters);

it only worked when i added all parameters
